---

- name: Restart filebeat
  service: name=filebeat enabled=yes state=restarted

- name: Restart topbeat
  service: name=topbeat enabled=yes state=restarted

- name: Restart packetbeat
  service: name=packetbeat enabled=yes state=restarted


